version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 60
      runas: ubuntu
