version: 2
jobs:
  pr_check:
    docker:
        - image: circleci/node:10.16.3  
    steps:
      - checkout
      - run:
          name: test
          command: echo "HELLO"

workflows:
  version: 2
  pr_check:
    jobs:
       - pr_check