version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  pr_check:
    docker:
      image: circleci/node:10.16.3  
    steps:
      - checkout
      - run:
          name: test
          command: echo "HELLO"

workflows:
  version: 2
  pr_check_test:
    jobs:
       - pr_check