version: 2.1
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.16.3  
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: npm-run-test
          command: npm test

  build:
    docker:
      - image: circleci/node:10.16.3 
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: npm-start
          command: npm start

workflows:
  version: 2
  pr_check_test:
    jobs:
       - pr_check
  build_and_deploy:
    jobs:
      - build